### ISSUE TITLE
Images are displayed correctly

### ISSUE THREAD

**Issue by palaniraja** [ogom/draw_uml#1]
Some images in [gh-pages](http://ogom.github.io/draw_uml/plantuml/) are not displayed correctly. Though the file seems to be there in /diagram path.

![screen shot 2017-05-01 at 9 29 47 pm](https://cloud.githubusercontent.com/assets/124864/25584955/d12186d2-2eb5-11e7-8732-e805d657ed7f.png)

eg., image path "http://ogom.github.io/draw_uml/assets/img/diagrams/parts/actor.png" did not fetch gh-pages  "https://github.com/ogom/draw_uml/blob/gh-pages/assets/img/diagrams/parts/actor.png"

**Comment by ogom** [comment]
Thank you. Fix the image path.
http://ogom.github.io/draw_uml/plantuml/
